created_at: '2025-08-21T03:57:22.118033'
frequency_penalty: 0.0
max_completion_tokens: 32768
max_history_size: 1000
model: gpt-4.1-mini
presence_penalty: 0.0
response_format: text
stream: true
system_prompt: null
temperature: 1.0
top_p: 1.0
updated_at: '2025-08-21T03:57:22.118041'
