created_at: '2025-08-21T03:59:01.726534'
frequency_penalty: 0.0
max_history_size: 1000
max_tokens: 32768
model: gpt-4.1
presence_penalty: 0.0
stream: true
system_prompt: null
temperature: 1.0
top_p: 1.0
updated_at: '2025-08-21T03:59:01.726539'
