created_at: '2025-08-21T04:32:04.445752'
frequency_penalty: 0.0
max_history_size: 1000
max_tokens: 32000
model: claude-opus-4-1-20250805
presence_penalty: 0.0
response_format: json
stream: true
system_prompt: you are agent
temperature: 1.0
top_p: 1.0
updated_at: '2025-08-21T04:32:04.445758'
