created_at: '2025-08-21T04:21:15.156354'
frequency_penalty: 0.0
max_history_size: 1000
max_tokens: 128000
model: claude-3-7-sonnet-20250219
presence_penalty: 0.0
response_format: json
stream: true
system_prompt: 'You are an agent '
temperature: 1.0
top_p: 1.0
updated_at: '2025-08-21T04:21:15.156358'
